edition = 2018
[package]
name = "jdjg-image-manipulation"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
imageproc = "0.24.0"
pyo3 = "0.21.2"
